#!/usr/bin/env python3
"""Merge multiple synthetic-augmentation roots into a single new root.

Concatenates raw/train.csv rows (preserving order), metadata.jsonl, and
optionally rejected.jsonl across input roots. Writes a fresh summary.json
recording provenance + the combined num_kept. Originals are left untouched.

Usage:
    python scripts/merge_synthetic_roots.py \\
        --inputs data/synthetic/crystalite_round1_msun_54k_v2 \\
                 data/synthetic/crystalite_round1_topup_1015 \\
        --output data/synthetic/crystalite_round1_msun_54k_v2_merged
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inputs", nargs="+", required=True, type=Path,
                    help="Two or more synthetic root directories to merge.")
    ap.add_argument("--output", required=True, type=Path,
                    help="Fresh output root. Must not exist.")
    args = ap.parse_args()

    if args.output.exists() and any(args.output.iterdir()):
        sys.exit(f"output exists and is non-empty: {args.output}")

    (args.output / "raw").mkdir(parents=True, exist_ok=True)

    # ---- merge raw/train.csv ----
    fieldnames = None
    all_rows: list[dict] = []
    per_input_counts: dict[str, int] = {}
    for root in args.inputs:
        csv_path = root / "raw" / "train.csv"
        if not csv_path.exists():
            sys.exit(f"missing {csv_path}")
        with csv_path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            if fieldnames is None:
                fieldnames = reader.fieldnames
            else:
                # ensure column compatibility
                if reader.fieldnames != fieldnames:
                    print(
                        f"[warn] column mismatch between roots: "
                        f"first={fieldnames}, {root.name}={reader.fieldnames}",
                        file=sys.stderr,
                    )
                    fieldnames = list(dict.fromkeys(
                        list(fieldnames) + list(reader.fieldnames)
                    ))
            count_before = len(all_rows)
            for row in reader:
                all_rows.append(row)
            per_input_counts[str(root)] = len(all_rows) - count_before

    out_csv = args.output / "raw" / "train.csv"
    with out_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in all_rows:
            writer.writerow({k: row.get(k, "") for k in fieldnames})
    print(f"[merge] wrote {len(all_rows)} rows to {out_csv}")

    # ---- concatenate metadata.jsonl (per-structure provenance) ----
    out_meta = args.output / "metadata.jsonl"
    with out_meta.open("w", encoding="utf-8") as fout:
        for root in args.inputs:
            meta = root / "metadata.jsonl"
            if not meta.exists():
                print(f"[warn] no metadata.jsonl in {root}, skipping",
                      file=sys.stderr)
                continue
            with meta.open("r", encoding="utf-8") as fin:
                for line in fin:
                    fout.write(line)
    print(f"[merge] wrote merged metadata.jsonl")

    # ---- merged summary.json ----
    summary = {
        "merged_from": [str(p) for p in args.inputs],
        "per_input_kept": per_input_counts,
        "num_kept": len(all_rows),
        "note": (
            "Generated by scripts/merge_synthetic_roots.py — concatenates "
            "raw/train.csv and metadata.jsonl from the listed inputs. "
            "Original roots untouched."
        ),
    }
    with (args.output / "summary.json").open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    print(f"[merge] summary.json written; total num_kept={len(all_rows)}")


if __name__ == "__main__":
    main()
